version: '3.4'

services:
  djangolabs:
    image: djangolabs
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    #command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./app/app:/workspaces/Django-labs/app/app
  db:
    image: postgres
    environment:
      POSTGRES_DB: salesforecast
      POSTGRES_USER: boukbab
      POSTGRES_PASSWORD: boukbab
    volumes:
      - pgdata:/var/lib/posgresql/data
volumes:
    pgdata:
